version: '3.9'

services:
    nginx:
        image: nginx:alpine
        ports:
            - "8000:8000"
        volumes:
            - nfs_share:/usr/share/nginx/html
        deploy:
            mode: replicated
            replicas: 3
            # update_config:
            #     parallelism: 1
            #     delay: 10s
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.role != manager

    postgres:
        image: postgres:14.4-alpine
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=siakad_pt
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints: [node.role != manager]

    php:
        image: zroni4/siakad:1.0
        ports:
            - "9000:9000"
        volumes:
            - nfs_share:/var/www/html
        deploy:
            mode: replicated
            replicas: 3
            # update_config:
            #     parallelism: 1
            #     delay: 10s
            restart_policy:
                condition: on-failure
            placement:
                constraints: [node.role != manager]
volumes:
    nfs_share:
        driver: local
        driver_opts:
            type: nfs
            o: addr=192.168.34.7,rw
            device: ":/srv/nfs_share/siakad"
    pg_data:
        driver: local
