version: '3.8'

# networks:
#     laravel:
#         driver: bridge

services:
    nginx:
        image: nginx:alpine
        # container_name: "nginx"
        # restart: unless-stopped
        # tty: true
        ports:
            - "8000:8000"
        volumes:
            - nfs_share:/usr/share/nginx/html
            # - ./:/var/www/app
            # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

            # - type: bind
            #   source: /mnt/nfs/share/nginx/default.conf
            #   target: /etc/nginx/conf.d/default.conf
            # - type: bind
            #   source: /mnt/nfs/share/app
            #   target: /var/www/html
        # depends_on:
        #     - php
        #     # - postgres
        # # networks:
        # #     - laravel
        # networks:
        #     - frontend
        deploy:
            mode: replicated
            replicas: 4
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.role != manager
        # deploy:
        #     replicas: 3
        #     restart_policy:
        #         condition: on-failure
        #     placement:
        #         constraints: [node.role != manager]

    postgres:
        image: postgres:14.4-alpine
        # container_name: "postgres"
        # restart: unless-stopped
        # tty: true
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data
            # - postgres_data:/var/lib/postgresql/data

            # - type: bind
            #   source: /mnt/nfs/share/postgres_data
            #   target: /var/lib/postgresql/data
        environment:
            - POSTGRES_DB=siakad_pt
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        # networks:
        #     - laravel
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints: [node.role != manager]

    php:
        # build:  migrate : php artisan migrate, seed : artisan db:seed
        #     context: .
        #     dockerfile: Dockerfile
        # image: laravel_docker:latest
        image: zroni4/siakad:1.0
        # container_name: "php"
        # restart: unless-stopped
        # tty: true
        # working_dir: /var/www/app
        # volumes:
        #     - ./:/var/www/app
        ports:
            - "9000:9000"
        volumes:
            - nfs_share:/var/www/html
            # - type: bind
            #   source: /mnt/nfs/share/app
            #   target: /var/www/html
        # networks:
        #     - backend
        deploy:
            mode: replicated
            replicas: 4
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure
            placement:
                constraints: [node.role != manager]
        # networks:
        #     - laravel
        # deploy:
        #     replicas: 1
        #     restart_policy:
        #         condition: on-failure
        #     placement:
        #         constraints: [node.role == manager]


    # redis_service:
    #     image: redis:7.0.9
    #     ports:
    #         - "6378"
    #     deploy:
    #         replicas: 1
    #         restart_policy:
    #             condition: on-failure
    #         placement:
    #             constraints: [node.role != manager]

volumes:
    nfs_share:
        driver: local
        driver_opts:
            type: nfs
            o: addr=<NFS_SERVER_IP>,rw
            device: ":/srv/nfs_share"
    pg_data:
        driver: local

#   postgres_data:
#     postgres_data:
#     nginx_conf:
#         external: false
#     app:
#         external: false
# networks:
#   frontend:
#   backend:

# nginx_data:
# letsencrypt_data:

    # redis:
    #     image: redis:alpine
    #     container_name: "${CONTAINER_PREFIX}_redis"
    #     ports:
    #         - "${REDIS_PORT}:6379"
    #     networks:
    #         - laravel
