
version: "3.9"

services:
#   database:
#     image: 192.168.10.2:5000/mariadb:10.5
#     restart: always
#     ports:
#       - 3306:3306
#     deploy:
#       replicas: 1
#     volumes:
#       - /mnt/nfsshare/docker/mariadb:/var/lib/mysql
#     environment:
#       - MYSQL_ROOT_PASSWORD:rootpassword
#       - MYSQL_DATABASE:mydb
#       - MYSQL_USER:user
#       - MYSQL_PASSWORD:userpassword

#   phpmyadmin:
#     image: 192.168.10.2:5000/phpmyadmin/phpmyadmin:latest
#     restart: always
#     ports:
#       - 8080:80
#     deploy:
#       replicas: 1
#     environment:
#       - PMA_ARBITRARY=1
#       - PMA_HOST=database
#     depends_on:
#       - database

  php:
    image: bitnami/php-fpm:7.4
    restart: always
    volumes:
      - /srv/nfs_share/siakad/tes:/usr/share/nginx/html
    deploy:
      replicas: 2

  webserver:
    image: nginx:1.19
    restart: always
    ports:
      - 8081:80
    volumes:
      - /srv/nfs_share/siakad/tes:/usr/share/nginx/html
    deploy:
      replicas: 2
    depends_on:
      - php# version: '3.9'

